import { createHash } from "node:crypto";
import { createAdminClient } from "@/lib/supabase/admin";
import { decryptCredential,encryptCredential } from "@/lib/crypto";
import { ProviderError } from "@/providers/errors";
import { PanoptoClient,refreshPanoptoToken,type PanoptoToken } from "./client";
import { parseTranscript,segmentTranscript } from "./transcripts";

export async function syncPanoptoCourse(courseId:string,ownerId?:string){const admin=createAdminClient();let query=admin.from("course_provider_links").select("owner_id,connection_id,external_id,provider_connections(base_url,status)").eq("course_id",courseId).eq("provider","panopto").eq("link_type","folder");if(ownerId)query=query.eq("owner_id",ownerId);const{data:link,error}=await query.maybeSingle();if(error||!link)throw new ProviderError("PROVIDER_MAPPING_MISSING","Course is not linked to a Panopto folder");const connection=link.provider_connections as unknown as{base_url:string;status:string};const key=process.env.MOODLE_ENCRYPTION_KEY;if(!key)throw new ProviderError("PROVIDER_AUTH_INVALID","Credential encryption is not configured");const{data:stored}=await admin.from("provider_credentials").select("encrypted_payload").eq("connection_id",link.connection_id).eq("owner_id",link.owner_id).single();if(!stored)throw new ProviderError("PROVIDER_AUTH_INVALID","Panopto credentials are unavailable");let token=await decryptCredential<PanoptoToken>(stored.encrypted_payload,key);
  if(token.expiresAt&&token.expiresAt<Date.now()+60_000){if(!token.refreshToken)throw new ProviderError("PROVIDER_AUTH_INVALID","Panopto authorization must be renewed");token={...await refreshPanoptoToken(connection.base_url,token.refreshToken),refreshToken:token.refreshToken};await admin.from("provider_credentials").update({encrypted_payload:await encryptCredential({...token},key)}).eq("connection_id",link.connection_id);}
  const client=new PanoptoClient(connection.base_url,token);const{data:legacyCapability}=await admin.from("provider_capabilities").select("available").eq("connection_id",link.connection_id).eq("capability_name","panopto_legacy_srt").maybeSingle();const allowLegacy=legacyCapability?.available===true;let page=0,seen=0,changed=0,unavailable=0;
  for(;;page++){const response=await client.sessions(link.external_id,page);const sessions=response.Results??[];if(!sessions.length)break;for(const summary of sessions){const session=summary.Urls?summary:await client.session(summary.Id);const{data:lecture,error:lectureError}=await admin.from("lectures").upsert({owner_id:link.owner_id,course_id:courseId,provider_connection_id:link.connection_id,provider_session_id:session.Id,provider_folder_id:session.Folder??link.external_id,title:session.Name??"Untitled lecture",recorded_at:session.StartTime??null,duration_seconds:session.Duration??null,instructor:session.CreatedBy?.DisplayName??null,provider_url:session.Urls?.ViewerUrl??null,transcript_source_modified_at:session.LastModified??null},{onConflict:"owner_id,provider_connection_id,provider_session_id"}).select("id").single();if(lectureError)throw lectureError;seen++;let transcript:{body:string;contentType:string}|null=null;try{transcript=await client.officialTranscript(session.Id);}catch(error){if(allowLegacy){try{transcript=await client.legacySrt(session.Id);}catch{transcript=null;}}else if(error instanceof ProviderError&&error.code!=="PROVIDER_FUNCTION_UNAVAILABLE")throw error;}if(!transcript?.body.trim()){await admin.from("lectures").update({transcript_status:"unavailable"}).eq("id",lecture.id);unavailable++;continue;}const cues=parseTranscript(transcript.body),rawText=cues.map((cue)=>cue.text).join("\n"),hash=createHash("sha256").update(rawText).digest("hex");const{data:existing}=await admin.from("lecture_transcripts").select("id,content_hash").eq("lecture_id",lecture.id).maybeSingle();if(existing?.content_hash===hash){await admin.from("lectures").update({transcript_status:"available"}).eq("id",lecture.id);continue;}const{data:record,error:transcriptError}=await admin.from("lecture_transcripts").upsert({owner_id:link.owner_id,lecture_id:lecture.id,raw_text:rawText,source_format:transcript.contentType.includes("vtt")?"webvtt":"srt",content_hash:hash,imported_at:new Date().toISOString()},{onConflict:"lecture_id"}).select("id").single();if(transcriptError)throw transcriptError;await admin.from("lecture_segments").delete().eq("lecture_id",lecture.id);const segments=segmentTranscript(cues);if(segments.length){const{error:segmentError}=await admin.from("lecture_segments").insert(segments.map((segment)=>({owner_id:link.owner_id,lecture_id:lecture.id,transcript_id:record.id,segment_key:segment.segmentKey,ordinal:segment.ordinal,start_seconds:segment.startSeconds,end_seconds:segment.endSeconds,text:segment.text,character_count:segment.characterCount,token_estimate:segment.tokenEstimate})));if(segmentError)throw segmentError;}await admin.from("lectures").update({transcript_status:"available"}).eq("id",lecture.id);changed++;}}return{courseId,folderId:link.external_id,sessionsSeen:seen,transcriptsChanged:changed,transcriptsUnavailable:unavailable};}
