import type { GradeCategory,GradeItem,GradeModel } from "./types";
export interface CategoryRule { gradeCategoryId:string; excluded:boolean; weightOverride:number|null }
export interface ItemRule { gradeItemId:string; excluded:boolean; scoreOverride:number|null; maximumScoreOverride:number|null }
export interface GradeCalculation { percentage:number|null; earned:number; possible:number; includedItems:number; excludedItems:number; categories:Array<{id:string|null;name:string;percentage:number|null;weight:number|null}>; warnings:string[]; target?:{targetPercentage:number;requiredRemainingPercentage:number|null;possible:boolean} }

export function calculateGrade(input:{categories:GradeCategory[];items:GradeItem[];model?:GradeModel|null;categoryRules?:CategoryRule[];itemRules?:ItemRule[];targetPercentage?:number}):GradeCalculation{
  const categoryRules=new Map((input.categoryRules??[]).map((rule)=>[rule.gradeCategoryId,rule]));const itemRules=new Map((input.itemRules??[]).map((rule)=>[rule.gradeItemId,rule]));const warnings:string[]=[];let excludedItems=0;
  const usable=input.items.flatMap((item)=>{const rule=itemRules.get(item.id);if(item.hidden||rule?.excluded){excludedItems++;return[];}const max=rule?.maximumScoreOverride??item.maximumScore;if(max===null||max<=0){warnings.push(`${item.name}: missing positive maximum score`);excludedItems++;return[];}const score=rule?.scoreOverride??item.score;if(score===null&&input.model?.ungradedPolicy!=="zero"){excludedItems++;return[];}return[{item,score:score??0,max,fraction:(score??0)/max}];});
  const byCategory=new Map<string|null,typeof usable>();for(const row of usable){const key=row.item.categoryId??null;byCategory.set(key,[...(byCategory.get(key)??[]),row]);}
  type Result={id:string|null;name:string;percentage:number|null;weight:number|null;earned:number;possible:number};const children=new Map<string,GradeCategory[]>();for(const category of input.categories){if(category.parentCategoryId)children.set(category.parentCategoryId,[...(children.get(category.parentCategoryId)??[]),category]);}
  const evaluate=(category:GradeCategory):Result|null=>{const rule=categoryRules.get(category.id);if(rule?.excluded)return null;const rows=byCategory.get(category.id)??[],childResults=(children.get(category.id)??[]).map(evaluate).filter((value):value is Result=>value!==null);const earned=rows.reduce((sum,row)=>sum+(row.score??0),0)+childResults.reduce((sum,row)=>sum+row.earned,0),possible=rows.reduce((sum,row)=>sum+row.max,0)+childResults.reduce((sum,row)=>sum+row.possible,0);const weightedElements=[...rows.filter((row)=>row.item.weight!==null).map((row)=>({percentage:row.fraction*100,weight:row.item.weight??0})),...childResults.filter((row)=>row.weight!==null&&row.percentage!==null).map((row)=>({percentage:row.percentage??0,weight:row.weight??0}))];let percentage=possible?earned/possible*100:null;if(weightedElements.length){const weight=weightedElements.reduce((sum,row)=>sum+row.weight,0);if(weight>0)percentage=weightedElements.reduce((sum,row)=>sum+row.percentage*row.weight,0)/weight;}if(category.aggregation&&!/natural|weighted|mean|sum/i.test(category.aggregation))warnings.push(`${category.name}: unsupported aggregation ${category.aggregation}; using normalized points/weights`);return percentage===null?null:{id:category.id,name:category.name,percentage,weight:rule?.weightOverride??category.weight,earned,possible};};
  const categoryResults:Array<Result>=input.categories.filter((category)=>!category.parentCategoryId).map(evaluate).filter((value):value is Result=>value!==null);
  const uncategorized=byCategory.get(null)??[];if(uncategorized.length){const earned=uncategorized.reduce((sum,row)=>sum+(row.score??0),0),possible=uncategorized.reduce((sum,row)=>sum+row.max,0);categoryResults.push({id:null,name:"Uncategorized",percentage:possible?earned/possible*100:null,weight:null,earned,possible});}
  let percentage:number|null=null;const weighted=categoryResults.filter((category)=>category.weight!==null&&category.percentage!==null);if(weighted.length){const total=weighted.reduce((sum,category)=>sum+(category.weight??0),0);if(total>0)percentage=weighted.reduce((sum,category)=>sum+(category.percentage??0)*(category.weight??0),0)/total;else warnings.push("Category weights sum to zero");}else{const earned=usable.reduce((sum,row)=>sum+(row.score??0),0),possible=usable.reduce((sum,row)=>sum+row.max,0);percentage=possible?earned/possible*100:null;}
  const earned=usable.reduce((sum,row)=>sum+(row.score??0),0),possible=usable.reduce((sum,row)=>sum+row.max,0);const result:GradeCalculation={percentage,earned,possible,includedItems:usable.length,excludedItems,categories:categoryResults.map(({id,name,percentage,weight})=>({id,name,percentage,weight})),warnings};
  if(input.targetPercentage!==undefined){const allMax=input.items.filter((item)=>!item.hidden&&!itemRules.get(item.id)?.excluded).reduce((sum,item)=>sum+(itemRules.get(item.id)?.maximumScoreOverride??item.maximumScore??0),0);const remaining=allMax-possible;const needed=input.targetPercentage/100*allMax-earned;const required=remaining>0?needed/remaining*100:null;result.target={targetPercentage:input.targetPercentage,requiredRemainingPercentage:required,possible:required!==null&&required>=0&&required<=100};if(remaining<=0)warnings.push("Target is underdetermined because no ungraded points remain");}
  return result;
}
