import assert from "node:assert/strict";import test from "node:test";import { MoodleClient } from "../src/providers/moodle/client.ts";import { MoodleLiveService,normalizeContents,readableHtml } from "../src/providers/moodle/live.ts";import { ProviderError,redactSecrets } from "../src/providers/errors.ts";import { extractDocumentText } from "../src/lib/document-extraction.ts";
test("Moodle requests use nested form encoding without putting tokens in URLs",async()=>{const original=globalThis.fetch;let capturedUrl="",capturedBody="";globalThis.fetch=async(input,init)=>{capturedUrl=String(input);capturedBody=String(init?.body);return new Response(JSON.stringify({ok:true}),{status:200,headers:{"content-type":"application/json"}});};try{await new MoodleClient("https://moodle.example.edu","secret-token",1000).call("example",{courseids:["42"],options:{visible:true}},0);assert.equal(capturedUrl,"https://moodle.example.edu/webservice/rest/server.php");const body=new URLSearchParams(capturedBody);assert.equal(body.get("courseids[0]"),"42");assert.equal(body.get("options[visible]"),"1");assert.equal(body.get("wstoken"),"secret-token");}finally{globalThis.fetch=original;}});
test("live module normalization classifies files and strips token-bearing URLs",()=>{const modules=normalizeContents([{id:1,name:"Week 1",modules:[{id:9,name:"Lecture",modname:"resource",url:"https://moodle.test/mod/resource/view.php?id=9&token=nope",contents:[{filename:"lecture.pdf",mimetype:"application/pdf",filesize:123,fileurl:"https://moodle.test/webservice/pluginfile.php/1/file.pdf?token=nope"}]}]}]);assert.equal(modules[0].files[0].filename,"lecture.pdf");assert.doesNotMatch(modules[0].url??"",/token=/);assert.doesNotMatch(modules[0].files[0].providerUrl??"",/token=/);assert.ok(modules[0].files[0].fileRef.length>20);});
test("announcement HTML becomes readable model text and secrets are redacted",()=>{assert.equal(readableHtml("<p>Hello &amp; welcome</p><ul><li>Read this</li></ul>"),"Hello & welcome\n\n- Read this");assert.doesNotMatch(redactSecrets("https://x.test?a=1&token=secret"),/secret/);});
test("file extraction supports plain text and rejects unsupported content",async()=>{assert.equal((await extractDocumentText(new TextEncoder().encode("course text"),"text/plain","notes.txt")).text,"course text");await assert.rejects(()=>extractDocumentText(new Uint8Array([1,2,3]),"video/mp4","lecture.mp4"),/Unsupported file content type/);});

test("Moodle downloads reject external, credential-bearing, and non-pluginfile URLs",async()=>{const original=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls+=1;return new Response("unexpected");};const client=new MoodleClient("https://moodle.example.edu/campus","secret",1000);try{for(const url of ["https://evil.example/webservice/pluginfile.php/1/x.pdf","https://user:pass@moodle.example.edu/campus/webservice/pluginfile.php/1/x.pdf","https://moodle.example.edu/campus/local/pluginfile.php/1/x.pdf"]){await assert.rejects(()=>client.downloadFile(url),(error:unknown)=>error instanceof ProviderError&&error.code==="FILE_REFERENCE_INVALID");}assert.equal(calls,0);}finally{globalThis.fetch=original;}});

test("Moodle downloads enforce declared and streamed byte limits",async()=>{const original=globalThis.fetch;const client=new MoodleClient("https://moodle.example.edu","secret",1000);try{globalThis.fetch=async()=>new Response("",{headers:{"content-length":"4"}});await assert.rejects(()=>client.downloadFile("https://moodle.example.edu/webservice/pluginfile.php/1/x.txt",3),(error:unknown)=>error instanceof ProviderError&&error.code==="FILE_TOO_LARGE");globalThis.fetch=async()=>new Response("four");await assert.rejects(()=>client.downloadFile("https://moodle.example.edu/webservice/pluginfile.php/1/x.txt",3),(error:unknown)=>error instanceof ProviderError&&error.code==="FILE_TOO_LARGE");}finally{globalThis.fetch=original;}});

test("readCourseFile validates a fresh course listing and preserves bounded pagination",async()=>{const oldContents=[{id:1,name:"Week",modules:[{id:9,name:"Old",modname:"resource",contents:[{filename:"old.txt",mimetype:"text/plain",filesize:3,fileurl:"https://moodle.example.edu/webservice/pluginfile.php/1/old.txt"}]}]}];const currentContents=[{id:1,name:"Week",modules:[{id:10,name:"Current",modname:"resource",contents:[{filename:"current.txt",mimetype:"text/plain",filesize:10,fileurl:"https://moodle.example.edu/webservice/pluginfile.php/1/current.txt?token=leak"}]}]}];const currentFile=normalizeContents(currentContents)[0].files[0];let listings=0,downloads=0;const client={courseContents:async()=>{listings+=1;return listings===1?oldContents:currentContents;},downloadFile:async(url:string)=>{downloads+=1;assert.doesNotMatch(url,/token=/);return{bytes:new TextEncoder().encode("0123456789"),contentType:"text/plain"};}};const service=new MoodleLiveService("owner-123",async(ownerId,courseId)=>{assert.equal(ownerId,"owner-123");assert.equal(courseId,"course-456");return{connectionId:"connection-789",providerCourseId:"provider-course",client:client as unknown as MoodleClient};});await service.getCourseModules("course-456");const result=await service.readCourseFile("course-456",currentFile.fileRef,2,4);assert.equal(listings,2);assert.equal(downloads,1);assert.equal(result.content,"2345");assert.equal(result.nextOffset,6);assert.equal(result.file.providerUrl,undefined);});

test("an invalid fileRef never reaches the Moodle downloader",async()=>{let downloads=0;const client={courseContents:async()=>[],downloadFile:async()=>{downloads+=1;throw new Error("must not run");}};const service=new MoodleLiveService("owner",async()=>({connectionId:"connection",providerCourseId:"course",client:client as unknown as MoodleClient}));await assert.rejects(()=>service.readCourseFile("course","not-a-listed-reference"),(error:unknown)=>error instanceof ProviderError&&error.code==="FILE_REFERENCE_INVALID");assert.equal(downloads,0);});
