import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { ConnectorPayloadError,MAX_TRANSCRIPT_BYTES,prepareIngestPayload,validateProviderUrl } from "../src/connectors/panopto/contract.ts";
import { extractBearerToken,generateConnectorToken,hashConnectorToken } from "../src/connectors/panopto/token.ts";
import { parseTranscript,segmentTranscript } from "../src/connectors/panopto/transcripts.ts";

const courseId="123e4567-e89b-42d3-a456-426614174000";
const content=`1\n00:24:15,000 --> 00:24:22,000\nProfessor says Quiz 3 will focus on branch prediction.\n\n2\n00:26:10,000 --> 00:26:18,500\nProfessor explains a branch predictor example.\n`;
const payload=(overrides:Record<string,unknown>={})=>({provider:"panopto",courseId,providerFolderId:"f0f2c21f-3fe0-432b-be56-b4a3005a4f59",providerSessionId:"9bc28a03-42b5-49da-9a1e-b4a3005a61d6",title:"2026 Fall ECE 463 001 09/02/26",recordedAt:"2026-09-02T14:30:00-04:00",durationSeconds:4731,providerUrl:"https://ncsu.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=9bc28a03-42b5-49da-9a1e-b4a3005a61d6",transcript:{format:"srt",language:"en",contentHash:createHash("sha256").update(content,"utf8").digest("hex"),content},...overrides});

test("connector tokens are high entropy, hash-only lookup values and strict Bearer credentials",()=>{const token=generateConnectorToken(),hash=hashConnectorToken(token);assert.match(token,/^ctx_panopto_[A-Za-z0-9_-]{43}$/);assert.match(hash,/^[0-9a-f]{64}$/);assert.equal(hash.includes(token),false);assert.equal(extractBearerToken(`Bearer ${token}`),token);assert.equal(extractBearerToken(null),null);assert.equal(extractBearerToken("Basic abc"),null);assert.equal(extractBearerToken("Bearer one two"),null);});
test("valid SRT connector payload verifies exact UTF-8 hash and builds searchable timed segments",()=>{const prepared=prepareIngestPayload(payload());assert.match(prepared.plainText,/Quiz 3 will focus on branch prediction/);assert.equal(prepared.segments[0].startSeconds,1455);assert.equal(prepared.segments.at(-1)?.endSeconds,1578.5);assert.match(prepared.segments.map((segment)=>segment.text).join(" ").toLowerCase(),/quiz 3.*branch prediction/);});
test("representative worker fixture completes caption-to-search preparation",async()=>{const fixturePath=fileURLToPath(new URL("./fixtures/panopto/ece463-september-2.srt",import.meta.url)),fixture=await readFile(fixturePath,"utf8"),prepared=prepareIngestPayload({...payload(),transcript:{format:"srt",language:"en",contentHash:createHash("sha256").update(fixture,"utf8").digest("hex"),content:fixture}});const match=prepared.segments.find((segment)=>/Quiz 3.*branch prediction/i.test(segment.text));assert.ok(match);assert.equal(match.startSeconds,1455);});
test("WebVTT parsing preserves order and timing while normalizing markup and entities",()=>{const cues=parseTranscript("WEBVTT\n\ncue-1\n00:00:01.000 --> 00:00:04.000 align:start\n<v Professor><b>Branch</b>&nbsp;prediction &amp; caches.</v>\n\n00:00:05.000 --> 00:00:08.000\nSecond line\ncontinues.","webvtt");assert.deepEqual(cues.map(({ordinal,startSeconds,endSeconds})=>({ordinal,startSeconds,endSeconds})),[{ordinal:0,startSeconds:1,endSeconds:4},{ordinal:1,startSeconds:5,endSeconds:8}]);assert.equal(cues[0].text,"Branch prediction & caches.");assert.equal(cues[1].text,"Second line continues.");});
test("segmentation is deterministic, chronological, caption-aware, and never splits a cue",()=>{const cues=Array.from({length:80},(_,ordinal)=>({ordinal,startSeconds:ordinal*10,endSeconds:ordinal*10+8,text:`Cue ${ordinal} ${"detail ".repeat(8)}`.trim()}));const first=segmentTranscript(cues,300,420),second=segmentTranscript(cues,300,420);assert.deepEqual(first,second);assert.ok(first.length>1);assert.deepEqual(first.map((segment)=>segment.ordinal),first.map((_,index)=>index));for(const segment of first){assert.ok(segment.startSeconds<=segment.endSeconds);for(const cue of cues.filter((item)=>item.startSeconds>=segment.startSeconds&&item.endSeconds<=segment.endSeconds))assert.match(segment.text,new RegExp(`Cue ${cue.ordinal}(?: |$)`));}});
test("payload validation rejects contract, corruption, URL, size and caption failures",()=>{const cases:Array<[string,unknown,string]>=[["provider",payload({provider:"moodle"}),"INVALID_PAYLOAD"],["course UUID",payload({courseId:"nope"}),"INVALID_PAYLOAD"],["timestamp timezone",payload({recordedAt:"2026-09-02T14:30:00"}),"INVALID_PAYLOAD"],["duration",payload({durationSeconds:0}),"INVALID_PAYLOAD"],["URL scheme",payload({providerUrl:"http://ncsu.hosted.panopto.com/x"}),"INVALID_PROVIDER_URL"],["URL host",payload({providerUrl:"https://evil.example/x"}),"INVALID_PROVIDER_URL"],["URL credential",payload({providerUrl:"https://user:pass@ncsu.hosted.panopto.com/x"}),"INVALID_PROVIDER_URL"],["URL token",payload({providerUrl:"https://ncsu.hosted.panopto.com/x?access_token=secret"}),"INVALID_PROVIDER_URL"],["hash",payload({transcript:{format:"srt",language:"en",contentHash:"0".repeat(64),content}}),"TRANSCRIPT_HASH_MISMATCH"],["malformed caption",payload({transcript:{format:"srt",language:"en",contentHash:createHash("sha256").update("not captions").digest("hex"),content:"not captions"}}),"MALFORMED_TRANSCRIPT"],["size",payload({transcript:{format:"srt",language:"en",contentHash:"0".repeat(64),content:"x".repeat(MAX_TRANSCRIPT_BYTES+1)}}),"TRANSCRIPT_TOO_LARGE"]];for(const[name,value,code]of cases)assert.throws(()=>prepareIngestPayload(value),(error:unknown)=>error instanceof ConnectorPayloadError&&error.code===code,name);});
test("configured provider origin comparison is exact",()=>{assert.doesNotThrow(()=>validateProviderUrl("https://panopto.example.edu/Panopto/Pages/Viewer.aspx?id=abc","https://panopto.example.edu"));assert.throws(()=>validateProviderUrl("https://panopto.example.edu.evil.test/x","https://panopto.example.edu"),/INVALID_PROVIDER_URL/);});
test("malformed and format-mismatched caption sources never become empty transcripts",()=>{assert.throws(()=>parseTranscript("WEBVTT\n\nnot a cue","webvtt"),/MALFORMED_TRANSCRIPT/);assert.throws(()=>parseTranscript(content,"webvtt"),/MALFORMED_TRANSCRIPT/);assert.throws(()=>parseTranscript("1\n00:00:05,000 --> 00:00:04,000\nbackwards","srt"),/MALFORMED_TRANSCRIPT/);});
test("migration defines atomic idempotency, owner mapping checks and service-only execution",async()=>{const sql=await readFile(fileURLToPath(new URL("../supabase/migrations/202609040011_panopto_connector.sql",import.meta.url)),"utf8");assert.match(sql,/pg_advisory_xact_lock/);assert.match(sql,/status := 'unchanged'/);assert.match(sql,/rebuild := existing_hash is distinct from p_content_hash/);assert.match(sql,/delete from public\.lecture_segments/);assert.match(sql,/connector folder mapping check failed/);assert.match(sql,/grant execute[\s\S]+to service_role/);});
